# Generated by Django 5.2.8 on 2026-06-04 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='department',
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название специальности')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Код специальности')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.department', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='specialty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journal.specialty', verbose_name='Специальность'),
            preserve_default=False,
        ),
    ]
