# Generated by Django 5.2.8 on 2026-06-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_remove_group_department_specialty_group_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, verbose_name='Квалификация'),
        ),
    ]
