# Generated by Django 5.2.8 on 2026-09-15 01:02

from django.db import migrations, models


def mark_existing_debts_required(apps, schema_editor):
    Grade = apps.get_model('journal', 'Grade')
    Task = apps.get_model('journal', 'Task')
    RequiredStudent = Task.required_students.through

    RequiredStudent.objects.bulk_create([
        RequiredStudent(task_id=task_id, student_id=student_id)
        for task_id, student_id in Grade.objects.filter(value=1).values_list(
            'task_id',
            'student_id'
        )
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_specialty_description_specialty_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='required_students',
            field=models.ManyToManyField(blank=True, related_name='required_tasks', to='journal.student', verbose_name='Обязательно для студентов'),
        ),
        migrations.RunPython(
            mark_existing_debts_required,
            migrations.RunPython.noop,
        ),
    ]
