# Generated by Django 5.2.8 on 2026-09-16 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_tasktype_task_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField(verbose_name='Год начала учебного года')),
                ('is_first_semester', models.BooleanField(default=True, verbose_name='Первый семестр')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Учебный семестр',
                'verbose_name_plural': 'Учебные семестры',
            },
        ),
        migrations.CreateModel(
            name='AcademicSemesterStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус учебного семестра',
                'verbose_name_plural': 'Статусы учебных семестров',
            },
        ),
        migrations.AddField(
            model_name='discipline',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждена'),
        ),
        migrations.AddField(
            model_name='disciplineplan',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Утверждён'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_graduated',
            field=models.BooleanField(default=False, verbose_name='Обучение завершено'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='duration_semesters',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Продолжительность обучения в семестрах'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterUniqueTogether(
            name='discipline',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='discipline',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='journal.academicsemester', verbose_name='Учебный семестр'),
        ),
        migrations.AlterUniqueTogether(
            name='discipline',
            unique_together={('plan', 'group', 'semester')},
        ),
        migrations.AddField(
            model_name='academicsemester',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.academicsemesterstatus', verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='GroupNumberSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название комплекта')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Комплект номеров групп',
                'verbose_name_plural': 'Комплекты номеров групп',
            },
        ),
        migrations.CreateModel(
            name='GroupNumberEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.PositiveSmallIntegerField(verbose_name='Курс')),
                ('name', models.CharField(max_length=50, verbose_name='Номер группы')),
                ('number_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='journal.groupnumberset', verbose_name='Комплект')),
            ],
            options={
                'verbose_name': 'Номер группы по курсу',
                'verbose_name_plural': 'Номера групп по курсам',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='number_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='journal.groupnumberset', verbose_name='Комплект номеров'),
        ),
        migrations.CreateModel(
            name='SpecialtyCurriculumItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_semester', models.PositiveSmallIntegerField(verbose_name='Семестр обучения')),
                ('plan', models.ForeignKey(limit_choices_to={'is_approved': True}, on_delete=django.db.models.deletion.PROTECT, to='journal.disciplineplan', verbose_name='План дисциплины')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Дисциплина учебного плана специальности',
                'verbose_name_plural': 'Дисциплины учебных планов специальностей',
            },
        ),
        migrations.CreateModel(
            name='StudentGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.group', verbose_name='Группа')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='journal.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'История группы студента',
                'verbose_name_plural': 'История групп студентов',
            },
        ),
        migrations.AddConstraint(
            model_name='academicsemester',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='academic_semester_dates_order'),
        ),
        migrations.AlterUniqueTogether(
            name='academicsemester',
            unique_together={('start_year', 'is_first_semester')},
        ),
        migrations.AlterUniqueTogether(
            name='groupnumberset',
            unique_together={('name', 'specialty')},
        ),
        migrations.AlterUniqueTogether(
            name='groupnumberentry',
            unique_together={('number_set', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='specialtycurriculumitem',
            unique_together={('specialty', 'study_semester', 'plan')},
        ),
        migrations.AddConstraint(
            model_name='studentgroupmembership',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='student_membership_dates_order'),
        ),
        migrations.AlterUniqueTogether(
            name='studentgroupmembership',
            unique_together={('student', 'start_date')},
        ),
    ]
