# Generated by Django 5.2.8 on 2026-09-16 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_academic_semester_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.academicsemester', verbose_name='Учебный семестр'),
        ),
        migrations.AlterField(
            model_name='group',
            name='number_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.groupnumberset', verbose_name='Комплект номеров'),
        ),
    ]
