# Generated by Django 5.2.8 on 2026-09-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_academic_semester_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplineplan',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
