# Generated by Django 5.2.8 on 2026-09-18 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_disciplineplan_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialtyCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('study_semester', models.PositiveSmallIntegerField(verbose_name='Семестр обучения')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Утверждён')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Учебный план специальности',
                'verbose_name_plural': 'Учебные планы специальностей',
                'unique_together': {('name', 'specialty', 'study_semester')},
            },
        ),
        migrations.AddField(
            model_name='specialtycurriculumitem',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='journal.specialtycurriculum', verbose_name='Учебный план'),
        ),
        migrations.CreateModel(
            name='AcademicSemesterCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_selections', to='journal.academicsemester', verbose_name='Учебный семестр')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semester_selections', to='journal.specialtycurriculum', verbose_name='Учебный план')),
            ],
            options={
                'verbose_name': 'Учебный план учебного семестра',
                'verbose_name_plural': 'Учебные планы учебных семестров',
                'unique_together': {('semester', 'curriculum')},
            },
        ),
    ]
