# Generated by Django 5.2.8 on 2026-09-18 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_regroup_curriculum_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='specialtycurriculumitem',
            unique_together={('curriculum', 'plan')},
        ),
        migrations.AlterField(
            model_name='specialtycurriculumitem',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='journal.specialtycurriculum', verbose_name='Учебный план'),
        ),
        migrations.RemoveField(
            model_name='specialtycurriculumitem',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='specialtycurriculumitem',
            name='study_semester',
        ),
    ]
