from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('student/', views.student_dashboard, name='student_dashboard'),
    path('student/profile/', views.student_profile, name='student_profile'),
    path('student/grades/', views.student_grades, name='student_grades'),
    path('student/tasks/', views.student_tasks, name='student_tasks'),
    path('lesson/<int:lesson_id>/', views.lesson_detail, name='lesson_detail'),
    path('student/attendance/', views.student_attendance, name='student_attendance'),
    path('teacher/', views.teacher_dashboard, name='teacher_dashboard'),
    path('teacher/profile/', views.teacher_profile, name='teacher_profile'),
    path('teacher/groups/', views.teacher_groups, name='teacher_groups'),
    path('teacher/journal/<int:discipline_id>/', views.teacher_journal, name='teacher_journal'),
    path('teacher/lesson/<int:schedule_id>/', views.teacher_lesson, name='teacher_lesson'),
    path('teacher/lesson/<int:lesson_id>/attendance/', views.teacher_lesson_attendance, name='teacher_lesson_attendance'),
    path('teacher/task/<int:task_id>/', views.teacher_task_grades, name='teacher_task_grades'),
    path('teacher/task/create/<int:lesson_id>/', views.teacher_task_create, name='teacher_task_create'),
    path('teacher/journal/export/<int:discipline_id>/', views.export_journal_excel, name='export_journal_excel'),
    path('teacher/journal/export/docx/<int:discipline_id>/', views.export_journal_docx, name='export_journal_docx'),
    path('admin/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/semesters/', views.admin_semesters, name='admin_semesters'),
    path('admin/semester/create/', views.admin_semester_create, name='admin_semester_create'),
    path('admin/semester/edit/<int:semester_id>/', views.admin_semester_edit, name='admin_semester_edit'),
    path('admin/curriculums/', views.admin_curriculums, name='admin_curriculums'),
    path('admin/curriculum/create/', views.admin_curriculum_create, name='admin_curriculum_create'),
    path('admin/schedules/', views.admin_schedules, name='admin_schedules'),
    path('admin/schedule/create/', views.admin_schedule_create, name='admin_schedule_create'),
    path('admin/schedule/edit/<int:schedule_id>/', views.admin_schedule_edit, name='admin_schedule_edit'),
    path('admin/schedule/delete/<int:schedule_id>/', views.admin_schedule_delete, name='admin_schedule_delete'),
    path('admin/discipline-plans/', views.admin_discipline_plans, name='admin_discipline_plans'),
    path('admin/discipline-plan/create/', views.admin_discipline_plan_create, name='admin_discipline_plan_create'),
    path('admin/discipline-plan/edit/<int:plan_id>/', views.admin_discipline_plan_edit, name='admin_discipline_plan_edit'),
    path('admin/discipline-plan/delete/<int:plan_id>/', views.admin_discipline_plan_delete, name='admin_discipline_plan_delete'),
    path('admin/discipline-plan/archive/<int:plan_id>/', views.admin_discipline_plan_archive, name='admin_discipline_plan_archive'),
    path('admin/disciplines/', views.admin_disciplines, name='admin_disciplines'),
    path('admin/discipline/create/', views.admin_discipline_create, name='admin_discipline_create'),
    path('admin/discipline/edit/<int:discipline_id>/', views.admin_discipline_edit, name='admin_discipline_edit'),
    path('admin/discipline/delete/<int:discipline_id>/', views.admin_discipline_delete, name='admin_discipline_delete'),
]